# Generated by Django 4.0.3 on 2022-03-24 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_movie_date_create'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='date_create',
            new_name='date_created',
        ),
    ]
